version: '3.8'

networks:
  global:

services:
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./server/mysql:/docker-entrypoint-initdb.d
    networks:
      - global

  adminer: 
    image: adminer:latest
    restart: "no"
    ports:
      - '8777:8080'
    depends_on: 
      - mysql
    links:
      - mysql

  web_server:
    depends_on:
      - frontend
      - books_service
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    ports:
      - "6969:80"

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend

  books_service: 
    image: composer:latest
    depends_on: 
      - mysql
    links:
      - mysql
    volumes: 
      - './backend/books/:/var/lib/mysql'
    networks:
      - global



