version: '3.8'

networks:
  global:
    driver: bridge

services:
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: '123qwe'
    volumes:
      - ./server/mysql:/docker-entrypoint-initdb.d
    networks:
      - global

  adminer: 
    image: adminer:latest
    restart: "no"
    ports:
      - '8777:8080'
    depends_on: 
      - mysql
    links:
      - mysql
    networks:
      - global
    
  frontend:
    stdin_open: true
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    networks:
      - global
    ports:
      - 3000:3000

  books_service: 
    build:
      context: ./backend/books
      dockerfile: Dockerfile
    depends_on: 
      - mysql
    links:
      - mysql
    volumes:
      - ./backend/books:/var/www/html
    networks:
      - global
    ports:
      - 8081:8000
