version: '3.8'

networks:
  global:
    driver: bridge

services:
  
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./server/mysql:/docker-entrypoint-initdb.d
    networks:
      - global

  adminer: 
    image: adminer:latest
    restart: "no"
    ports:
      - '8777:8080'
    depends_on: 
      - mysql
    links:
      - mysql
    networks:
      - global

  web_server:
    depends_on:
      - frontend
      - books_service
    links:
      - frontend
      - books_service
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    ports:
      - "6969:80"
    volumes:
      - ./backend/books:/var/www/books
    networks:
      - global

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/usr/src/frontend
    networks:
      - global

  books_service: 
    build:
      context: ./backend/books
      dockerfile: Dockerfile
    depends_on: 
      - mysql
    links:
      - mysql
    volumes:
      - ./backend/books:/var/www/html
    networks:
      - global



