import type { GetServerSideProps } from "next";
import Head from "next/head";
import { useEffect } from "react";
import { Button, Card, Col, Container, Row } from "react-bootstrap";

export const getServerSideProps: GetServerSideProps = async () => {
  const books = await fetch(`${process.env.NEXT_PUBLIC_SITE_URL}/api/hello`);
  const data = await books.json();
  return {
    props: { data },
  };
};

export default function Home({ data }: any) {
  useEffect(() => {
    console.log(data);
  }, []);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Row>
            {data.data.map(({ id, title, description, latest_edition }, index) => (
              <Col md={3} key={id}>
                <Card>
                  <Card.Img variant="top" src={latest_edition.image_path} />
                  <Card.Body>
                    <Card.Title>{title}</Card.Title>
                    <hr />
                    <Card.Text>{description}</Card.Text>
                  </Card.Body>
                </Card>
              </Col>
            ))}
          </Row>
        </Container>
      </main>
    </>
  );
}
